name: CI & Deploy

on:
  push:
    branches:
      - dev
  workflow_dispatch:  # manual trigger

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Init - Install Dependencies
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Init - npm install and setup
      run: |
        node -v
        npm install

    - name: Test - Run unit tests
      continue-on-error: true
      run: |
        npm run testLinux

    - name: Deploy Spotwise Frontend with Docker Compose
      run: |
        echo "Running on $(hostname)"
        cd /home/cs144/spotwise/SpotwiseFrontend && docker pull
        cd /home/cs144/spotwise/SpotwiseBackend && docker pull
        cp -f /home/cs144/spotwise/SpotwiseFrontend/Dockerfile /home/cs144/
        cd /home/cs144/spotwise
        docker compose up --build -d



